"""Increase password_hash length

Revision ID: 67056f24e090
Revises: 8e9b4391c64e
Create Date: 2025-08-03 19:55:39.722177

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "67056f24e090"
down_revision = "8e9b4391c64e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=300),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=300),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
