"""Auto migration

Revision ID: 8e9b4391c64e
Revises: 
Create Date: 2025-08-03 19:13:47.334507

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e9b4391c64e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("phone", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("user_type", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("job_title", sa.String(length=40), nullable=True))
        batch_op.add_column(
            sa.Column("photo_filename", sa.String(length=128), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("photo_filename")
        batch_op.drop_column("job_title")
        batch_op.drop_column("user_type")
        batch_op.drop_column("phone")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
