"""add fields

Revision ID: ece97d0621d3
Revises: 67056f24e090
Create Date: 2025-11-13 11:59:24.647821

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ece97d0621d3"
down_revision = "67056f24e090"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("order_number", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(
            sa.Column("total_sum", sa.Numeric(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("full_name", sa.String(length=120), nullable=True)
        )
        batch_op.add_column(sa.Column("phone", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("email", sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column("company_name", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("comment", sa.Text(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_order_order_number"), ["order_number"], unique=True
        )

    with op.batch_alter_table("order_item", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("product_name", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("article", sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("sum", sa.Numeric(precision=10, scale=2), nullable=True)
        )
        batch_op.alter_column("product_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column(
            "article",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=10),
            existing_nullable=False,
        )
        batch_op.drop_column("our_opinion")
        batch_op.drop_column("complete_set")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "complete_set",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "our_opinion",
                sa.VARCHAR(length=1000),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.alter_column(
            "article",
            existing_type=sa.String(length=10),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("order_item", schema=None) as batch_op:
        batch_op.alter_column("product_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("sum")
        batch_op.drop_column("price")
        batch_op.drop_column("article")
        batch_op.drop_column("product_name")

    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_order_number"))
        batch_op.drop_column("comment")
        batch_op.drop_column("company_name")
        batch_op.drop_column("email")
        batch_op.drop_column("phone")
        batch_op.drop_column("full_name")
        batch_op.drop_column("total_sum")
        batch_op.drop_column("order_number")

    # ### end Alembic commands ###
